### ISSUE TITLE
Hardware tab ist empty

### ISSUE THREAD

**Issue by ffactory-ofcl** [RainwayApp/bug-tracker#12]
As can be seen [here](https://i.imgur.com/Mmd9983.png):

![](https://i.imgur.com/Mmd9983.png)

the hardware tab is completely empty and there are no dropdowns where one should be able to select encoder etc.
I'm running an i7 with a GTX980 on windows 10 Fall Creators update and this occurred on versions 0.1.0 and 0.1.1 but I can't test it on 0.1.2 because I can't log in.

[Server.log](https://github.com/RainwayApp/bug-tracker/files/1649357/Server.log)
[settings.json.txt](https://github.com/RainwayApp/bug-tracker/files/1649360/settings.json.txt)
[Radar.log](https://github.com/RainwayApp/bug-tracker/files/1649361/Radar.log)

**Comment by Codeusa** [comment]
Hi, can you confirm if you're running  Windows 10 N?

And can you verify if you have this installed https://support.microsoft.com/en-us/help/4039813/media-feature-pack-for-windows-10-n-october-2017

**Comment by roman380** [comment]
"2018-01-20 17:31:18,160 [1] WARN Rainway.Core.Windows.Hardware.HardwareInfo - Found no displays from COM." is indeed likely to be caused by Windows 10 N version. As we don't print this information in our logs, here is a simple way to identify whether your Windows is an N variant:

Press Win+R, type "winver" and press Enter to run. 

![untitled](https://user-images.githubusercontent.com/11475832/35188887-d9ad76f0-fe47-11e7-9e64-e41e528b2003.png)

Red arrow shows where "N" version is printed, and also the magenta arrow shows Windows 10 version, which we expect to be Version 1709 and build 16299.xxx or higher (that is the image above shows version prior to Fall Creators Update).

**Comment by ffactory-ofcl** [comment]
[It's the enterprise edition.](https://i.imgur.com/Ag662th.png). I'm not sure why I bought that one but that was a long time ago and the point is it's not the N version.

**Comment by ffactory-ofcl** [comment]
Okay I thought that I had the Fall Creators Update installed but apparently I haven't. I'm downloading it as I'm writing this and will report back once it's installed. It was quite difficult to convert the enterprise edition (which is what was preventing me from updating) to the pro edition but it worked.

**Comment by subjectdenied** [comment]
this makes it impossible currently to use rainway on cloudservices like paperspace

**Comment by ffactory-ofcl** [comment]
It works! The hardware tab shows all my hardware and although it needs some cleaning (the display name is \\.\Display1) the stream works more or less okay. The issue is resolved and there never was an issue in the first place since I wasn't running the Fall Creators update as is required by the program.
It would be good to mention this while installing though since most users probably don't know if their windows is up to date.
