### ISSUE TITLE
Computer automatically wakes at 1am after Rainway server is installed or updated

### ISSUE THREAD

**Issue by redion1992** [RainwayApp/bug-tracker#130]
Steps to reproduce:
1. Install or update Rainway
2. Put computer in sleep or hibernate modes
3. Wait until 1am

At this point, the computer automatically wakes in order to update Rainway using a scheduled task (as proven by the output of `powercfg /lastwake`).

The current workaround is to go to Task Scheduler, find the task (in the Task Scheduler Library folder, named RainwayUpdater) and modify the task properties to disable “Wake the computer to run this task”. To maintain the automatic updates, it is also advisable to enable the setting “Run task as soon as possible after a scheduled start is missed”. However, this task is reset to its defaults on installing an update to Rainway, requiring using the workaround again. It would improve the user experience by modifying the installed task in this way, so that computers are not automatically woken without the user’s knowledge or permission.

Windows 10 1709, x64.

**Comment by derula** [comment]
This is not an "enhancement," it's a quite critical bug. Why?

1. If the computer is hooked up to a multi socket that is turned off during the night, Rainway will never run the updates.
2. If people turn off their router during the night, the computer will turn on but be unable to perform any updates*.
3. As @redion1992 says, if the update fails, the task will not be re-tried later, and no update will be performed.
4. After the task is run, the computer will not be turned off again**, wasting the user's electricity (and money).
5. If the user is like me, they'll be woken up at night multiple times, and take a long time to research the problem, messing with their sleep schedule and just generally annoying them.
6. _No other update task on my machine does this._ Not even Windows updates are that important.

I really like the idea of Rainway, and if this isn't fixed, I'll have to uninstall it and not use it. It's not _that_ great that it's worth waking up every night for (or routinely checking the scheduled tasks to see if it turned itself on again).

Okay, going back to sleep...

\* I noticed that the option "Start only if [a] network connection is available" is set. That does not keep it powered off in this case. I'm assuming it only checks if a network cable is connected and not if it's actually providing Internet access.

** Yes, you can set the PC to turn of automatically after a while. This is not a solution. It might end up in standby with aggressive blinking lights. If the computer was in hibernation with a paused video, it may not even go to standby because the video player can prevent that.

**Comment by Codeusa** [comment]
Fixed

**Comment by Jimmy3J** [comment]
Hello. I'm here to report if you are in the case were you uninstalled Rainway before your update was implemented, the planified task is still running:
![bugged](https://user-images.githubusercontent.com/31630985/37881127-64bd3622-3093-11e8-88fa-3b0062052ff8.PNG)

My system is in french, but you can clearly see the date of the executed task and the Windows error 0x80040002 meaning that "the specified file cannot be found"

For a little background: I've uninstalled Rainway because this bug caused my computer to wake up from sleep and this behaviour started right after the installation of the product, so I had strong suspicions about the source of this behaviour being Rainway.

Yet tonigh, after it kept happening, I decided to Google my problem and found the "powercfg /lastwake" command wich pointed me to the culprit.

I may not be the only one in this case. May I suggest sending an e-mail to signal this to the other users ?

**Comment by Codeusa** [comment]
This isn't a bug. Its a preference.
