### ISSUE TITLE
Client Black Screen after launching Steam Game

### ISSUE THREAD

**Issue by PapaGaymer** [RainwayApp/bug-tracker#19]
After having launched Rainway on the Desktop (server) and logged into Rainway on my laptop (client), I chose to launch Bridge Constructor Portal from the client.

The game launches server side, but client side in Mozilla, all I have is a black screen.

**Comment by progranadegrinder** [comment]
I have the same exact issue on my Android phone with Chrome and my Chromebook. The client is always black, and there's no audio. I've cleared cache, rebooted, tried different games, tried launching the desktop, nothing works.

**Comment by notdisliked** [comment]
I'm getting this as well, tried Chrome stable, Chrome beta, and Firefox stable.  Also tried all available encoders.

**Comment by tuytuyutoy9** [comment]
not sure if this helps but i was getting this on all my systems too but using intel quick sync encoder made it work

**Comment by tuytuyutoy9** [comment]
i have a r7 1700 gtx 1070 with a 3 monitor setup doesnt matter what encoder i use
 a laptop intel i7 with a gt 740m switching to quick sync works for this

**Comment by notdisliked** [comment]
Server is an i7 4770k with a GTX 1080. Two monitor setup, main is 1080p144, 2nd is 1080p60. Tried all encoders, none work.

**Comment by roman380** [comment]
@tuytuyutoy9, @notdisliked,
The monitor you have selected in Rainway settings to stream from - is it checked as "make this my main display" under Display settings, Multiple displays? Or, if not, did you happen to try to either stream from main display or set this display as main?

**Comment by tuytuyutoy9** [comment]
the monitor is set as main

**Comment by skywalkersmith** [comment]
I got stardew valley to load using software encoder but the response time is pretty bad. (Lag)

I can’t get it to work with the Nvidia encoder though... it’s just a black screen with sound and I can see my mouse moving on the host nearly 1:1. 

I also have a 3 monitor setup and just set the main monitor as the stream source just if that matters

**Comment by zehnzen** [comment]
i5 7600k with Gtx 1080, tried selecting the quick sync encoder with the HD graphics 630. Didn't actually plug any monitor into that one tho so that might also cause the quick sync to not work.
Benq XL2411Z 144 hz monitor.

**Comment by progranadegrinder** [comment]
I7 7700k, 1080ti, triple monitor setup, not all lined up tho. 2 of then are 60hz one of them is 144hz

**Comment by Jessomadic** [comment]
I was told by Jonathan to post my specs here. (i5-7600k (5.1Ghz) 16Gb Ram (2400mhz) 1060 6Gb(2000 Mhz)

**Comment by roman380** [comment]
We are seeing issues related to system with Nvidia hardware and multi-monitor setup. There is one severe problem in scenarios with main display being not connected to such Nvidia adapter, in which case Nvidia encoder fails to take off (esp. when error 0x8000FFFF is printed deep in logs). In this scenario software encoder option is working even though performance is of course far from being good (this just helps us understand that the problem is isolated to Nvidia encoder).

However, the comments above suggest that there is something else as well (specifically you guys mentioned that you have GTX systems with primary monitors plugged into them), and those are probably on our side. With next push we hope to have some more diagnostic information printed in order to address these issues.

**Comment by Jessomadic** [comment]
So should I try to unplug my second monitor to see if it helps?

**Comment by roman380** [comment]
If it happens that your display which you try to stream is not the main display, then it is worth trying to make it main. To do so, one needs to right click desktop and choose Display Settings, then click display in question and under "Multiple Displays" below check box "Make this my main display" if it is not checked. To our best knowledge this is only applicable to Nvidia cards.

Other than this, it would also help if you download this tool [MediaFoundationDxgiCapabilities.exe](http://www.alax.info/svn/public/trunk/Toolbox/MediaFoundationDxgiCapabilities-x64.exe) and run it. The app will show video adapter related data (text) once started. You could click Update button holding Control key pressed, and the text will be updated AND becomes editable - so that you could add a link to this ticket and/or add any other related info. Once Submit button is clicked, we will get the data. Thanks!

**Comment by zehnzen** [comment]
Somehow the Software option is working for me now even though I tried that one as well when I posted my earlier comment.

**Comment by progranadegrinder** [comment]
https://pastebin.com/hP8KQMcq
I updated my drivers and I was able to get the stream working in Firefox but not in Chrome. Once I restarted my computer Firefox wouldn't stream anymore.

**Comment by tuytuyutoy9** [comment]
https://pastebin.com/DJPj7PjU

**Comment by Codeusa** [comment]
@zehnzen as a quick test, can you set the audio adapter to the one causing the issue again and then browse to C:\Windows\System32\config\systemprofile\AppData\Roaming\RainwayInc\Server

Open the settings.json and set  "DisableAudio" to true

Restart Rainway and let us know if the stream works.

**Comment by Deathedit** [comment]
Temp fix for black screen that works for me

What I did to make it work

1. Display and Audio Settings need to be the same in rainway ![Like this](https://i.imgur.com/4muemVV.png)
2. make sure you enable your monitor audio in windows settings ![Like this](https://i.imgur.com/06rk8qQ.png)

**Comment by MrPokeboy8** [comment]
I've got two audio settings, NVIDIA hdmi audio and "speakers" (front headphone jack).
Setting the audio to Nvidia Audio gets me the first frame of the stream and nothing else.
Setting the audio to Speaker has a black screen.

**Comment by zehnzen** [comment]
@Codeusa I disabled the audio in the settings file as you described and using any audio source now let's it stream on the nvidia encoder as I showed earlier.

**Comment by roman380** [comment]
I'd say it might also work (as a temporary fix) if you don't change the device or you just have a single device, and you click Properties, and there on Advanced tab choose a stereo configuration. I suppose that the root cause is those of you guys who have issues have 5.1 there or similar.

**Comment by christianle123** [comment]
I don't even see anything in the "Headware" tab
![udklip](https://user-images.githubusercontent.com/35665514/35197463-bb666998-fedf-11e7-95da-3cd94828be25.PNG)

**Comment by roman380** [comment]
@christianle123 you might have #12 issue?

**Comment by christianle123** [comment]
@roman380 Yea, thank you for linking the issue

**Comment by Incognymous** [comment]
Some Nvidia graphics cards can't use the NVENC or the Nvidia H.246 encoder, specifically the ones with a GM108 chip, and streaming using the Nvidia encoder will cause a black screen. Switching to Intel Quick Sync will resolve the problem.

**Comment by Codeusa** [comment]
We've pushed an update that should resolve this, can someone confirm? Download 0.1.6 from the website or update from the start menu.

**Comment by notdisliked** [comment]
No such luck for me, still black screen.

**Comment by tuytuyutoy9** [comment]
im still getting a black screen with the new update using a logitech g933 headset

**Comment by James76931** [comment]
I'm also still getting black screen issues.

**Comment by Jessomadic** [comment]
Going to the windows screen setting and making it my main display fixed my
issue.

**Comment by notdisliked** [comment]
Scratch that, Software encoder still does the black screen issue, but Nvidia encoder works now (just very laggy).

**Comment by roman380** [comment]
@tuytuyutoy9  can you please check in that list of devices, under properties, Advanced tab (screenshot is [here](https://stackoverflow.com/a/48336308/868014), disregard the question itself - just screenshot is relevant under red frame) maybe you have 44100 on your headset device, and there is no 48000 Mono/Stereo option? I thought I might have missed 44100 that needs resampling for online streaming...

**Comment by tuytuyutoy9** [comment]
its currently using 48000hz

**Comment by aurum-codex64** [comment]
The nvidia encoder still displays a black screen an my part, with no audio. Inputs are still sent, however. Software encoding same thing; no audio/video, but inputs work.  The intel encoder works, but suffers from heavy lag. I am using a laptop as a host machine, so that might have something to do with it.
Specs: Intel Core i7-5700HQ and NVidia GTX 965M.

**Comment by tuytuyutoy9** [comment]
not sure what has changed but restarting my computer fixed it

**Comment by bluedory86** [comment]
Still black screen for me. Tried disabling audio but did not work.

**Comment by Jessomadic** [comment]
@bluedory86 have you updated Rainway now? They added a fix for the Black Screen Issue but the Nvidia x264 encoder is still very broken. Causing anywhere from 200-500ms Ping. Using the software Encoder helps to a point of making games playable at the expense of only being able to run lower tier games as you are doing everything off of your CPU (Unless you have a really nice APU)

**Comment by 1tyler101** [comment]
i too am having the black screen issue though I'm using a laptop Acer Aspire v nitro  i7-4720HQ 8gb ram with Nvidia gtx 960m.  i can get the stream to work if i use the  intel quick sync but it vary laggy and no audio no mater how i change the settings 
![screenshot 77 _li_moment_moment](https://user-images.githubusercontent.com/35754691/35314765-1e379440-007d-11e8-837c-2f5f93cc4048.jpg)
