### ISSUE TITLE
[Mac OS] Video output freeze on virtual desktop change

### ISSUE THREAD

**Issue by MarkoBuxar** [RainwayApp/bug-tracker#277]
# Title

Video sometimes completely freezes on virtual desktop change on Mac OS, input still works as intended

## Steps

- Connect to the host pc (desktop control, game...)
- Switch virtual desktops 
- focus a different app
- Interact with the other app
- switch back to rainway client 
- repeat if necessary

## What happens

Video output completely freezes on the last visible frame, input still works

## What is expected

Video output and input work as expected

## Host

 - OS: Windows 10 Home
 - Version: 1803
 
## Browser

 - OS: macOS Mojave
 - Version: 10.14.2 (18C54)
 - Browser: Google Chrome
 - Browser Version: 72.0.3626.109 (Official Build) (64-bit)

**Comment by apecoraro** [comment]
Hi Marko, I wasn't able to reproduce this issue using a Mac mini version 10.14.4 and the Google Chrome version 73.0.3683.86 (Official Build) (64-bit). First thing you might try is upgrading to the newer versions of the OS and browser.

I was testing with Doom and the procedure I was using to reproduce the bug was the following:

1. Start the game and go into Arcade mode.
2. Use the keyboard shortcut to bring up Mission Control.
3. Click on a different virtual desktop.
4. Interact with a window in the other virtual desktop.
5. Keyboard shortcut to bring up Mission Control again.
6. Click on the virtual deskop of the game again.
7. Repeat a bunch of times.

Were you using a different procedure than the above? If so, please provide more specific instructions.

Or perhaps it has to do with a particular game? Are you able to reproduce the issue in more than one game and which ones?

Thanks.

**Comment by MarkoBuxar** [comment]
Thank you for the response, it seems that the bug has since been somehow fixed. I don't know what caused the issue in the first place, but I haven't experienced it in a while, and am not able to reproduce it at the moment. Now, the video does not freeze, and if it does, it only does so for a second or so untill it catches up with the video stream. I'd probably most likely attribute it to the now old (at the time up-to-date) chrome version.
