### ISSUE TITLE
Cannot download the Rainway client in firefox

### ISSUE THREAD

**Issue by Sixmorphugus** [RainwayApp/bug-tracker#292]
# Cannot download the Rainway client in firefox

I do not know if this worked in a previous version

If you navigate to the Rainway website in Firefox, Waterfox, or some other version of the Firefox browser, the wrong version (v0.0.0000) of Rainway is shown and you cannot start downloaded rainway, even with the try again button on the download page.

## Steps

- Using Firefox/Waterfox, visit the Rainway homepage. You should see this:
![bad version](https://media.discordapp.net/attachments/341541173824847873/552533993468461069/unknown.png)
- Attempt to download Rainway. Even if you click "Try Again", your download will not start.

## What happens

See **Steps**.

## What is expected

I expected what happens in Chrome to happen:
- Version number shown correctly (v1.0.6.0)
- Download starts upon pressing "Download Now"

## Host

 - OS: Windows 10 Pro
 - Version: 1809
 
## Browser
N/A
 
## Logs
N/A

**Comment by Codeusa** [comment]
Can you load https://releases.rainway.com/Installer_current.json in your browser?

**Comment by Sixmorphugus** [comment]
![image](https://user-images.githubusercontent.com/7923357/53842861-92ae8300-3f98-11e9-8e38-665678726d20.png)

I get this in Waterfox.

**Comment by agentd00nut** [comment]
This is caused by that json file not being encoded "properly".

JSON files are supposed to be encoded as UTF-8.  

Our file is being encoded as UTF16LE which places a byte order marker (FF FE) bytes at the front of the file.

Firefox is seeing these bytes and isn't properly ignoring them the way that chrome and other browsers apparently do.

I converted the encoding of the file and firefox was able to read it fine, but moving forward whoever generates that file ( i don't ) needs to make sure the encoding is UTF-8.
