### ISSUE TITLE
Server setup window will reopen when closed

### ISSUE THREAD

**Issue by healingbrew** [RainwayApp/bug-tracker#3]
source: discord (caution)

**Comment by BetaLeaf** [comment]
I also experience this. For me, it happens everytime I shut down my computer. As a result, I either have to force a restart or wait for the timeout to force it automatically. I believe this is because the Rainway Radar service is detecting Rainway.exe has closed and restarts it, which is intended behavior, but fails to recognize a 1074 shutdown event. @Codeusa on your service, check if a 1074 event was logged within the last 15 seconds during the routine that restarts Rainway.exe. If true, run exit routine.
