### ISSUE TITLE
gamepad not detected

### ISSUE THREAD

**Issue by marci012** [RainwayApp/bug-tracker#302]
# Title

gamepad not detected on remote computer

## Some description

the controller is connected to the computer. the computer detect it as a xbox controller. rainway does not detect the controller and still display no gamepad. the same gamepad work on my phone.

## What is expected

i expect my controller to be detected like it did on my phone

## Host

 - OS: [e.g. Windows 10]
 - Version: [e.g. 8115]
 
## Browser

 - Browser: [e.g. google chrome]
 - Browser Version: [e.g. latest version]

**Comment by lynn** [comment]
You might have to wiggle a stick or press a button on the controller after plugging it in. For privacy reasons, the browser hides the gamepads from Rainway until the user tries to use them.

Can you please try these steps for me?

1. With your gamepad plugged in, open a new browser tab in Chrome.
2. Press **Ctrl + Shift + J** to open the JavaScript console.
3. Input `navigator.getGamepads()` and hit Enter.
4. Expand the results and take a screenshot of 'em so that the `id` fields are visible:

![image](https://user-images.githubusercontent.com/16232127/54963037-6eedb580-4f24-11e9-83e2-745972977152.png)

Again, if the gamepad entries are all `null`, press some buttons on the pad and try steps 3 and 4 again.

**Comment by marci012** [comment]
Hi,
Thanks for the feedback. For some reason I didn't have to do these steps and it started to detect the controller today. Thanks for helping

**Comment by lynn** [comment]
Glad to hear it! Thanks for letting us now. :sparkles:
