### ISSUE TITLE
Support page https://rain.gg/e/SocketConnectionError infinitely redirects on multiple systems and multiple networks.

### ISSUE THREAD

**Issue by BetaLeaf** [RainwayApp/bug-tracker#329]
Support page https://rain.gg/e/SocketConnectionError infinitely redirects on multiple systems and multiple networks.  I've tried clearing cookies and cache, even went so far as to try incognito mode. This sounds like a server misconfiguration to me. This link is shown on Rainway Host when Rainway fails to establish a websocket connection. (during startup, not on session). Was instructed by Jon on discord to report the issue.

**Comment by agentd00nut** [comment]
rain.gg uses page rules to control how it redirects to rainway.com.

Which means you can't just replace "www.rainway.com" with "rain.gg" and have it work...

So for this example there was no "rain.gg/e/" page rule setup...
In addition we only get so many page rules, though they can use regex.  So if we want "rain.gg/e/someError" to redirect to help pages that's fine but "someError" should be the actual name of the rainway.com/support/ page.

So for this example instead of "rain.gg/e/SocketConnectionError" we should be showing "rain.gg/e/unabletoconnect" because that will get changed into "rainway.com/support/unabletoconnect" which is an actual help article.


So i've setup "rain.gg/e/" to forward to "rainway.com/support/" and put on whatever comes next, but obviously find the support article and use its path to make sure you redirect to the proper support articles...
Of course its possible if we really want to use "SocketConnectionError" to set that specific rule to point to the proper article, it just uses up one of our rules (which we can buy more of).

**Comment by BetaLeaf** [comment]
> Which means you can't just replace "www.rainway.com" with "rain.gg" and have it work...
~ agentd00nut 

Yea, I didn't change the url. I clicked the link Rainway app gave me when I got the error.

> This link is shown on Rainway Host when Rainway fails to establish a websocket connection. (during startup, not on session).
~ BetaLeaf

_____

>So i've setup "rain.gg/e/" to forward to "rainway.com/support/" and put on whatever comes next, but obviously find the support article and use its path to make sure you redirect to the proper support articles...
~ agentd00nut

I see the change on my end. Did you also change the link that is given when Rainway Host fails to establish a websocket connection?

**Comment by BetaLeaf** [comment]
P.S. I've been using Rainway Host and Rainway app interchangeably. Let me know if this is wrong and what I should call it.

**Comment by healingbrew** [comment]
Should no longer redirect infinitely, but that support page didn't exist to begin with.
