### ISSUE TITLE
Black Screen when using hardware encoding with NVIDIA GPU and their fresh driver

### ISSUE THREAD

**Issue by sa3eedo12** [RainwayApp/bug-tracker#375]
Hi, 
I've tried using rainway clients on both my xbox and iPhone, unless I use software encoding, my stream would always be blank.

Here's my config:

intel i7 8700K
RTX 2080Ti
Asus MX34" Ultrawide monitor
HDMI Audio

**Comment by roman380** [comment]
Did you have a chance to see if playing from remote PC (Chrome browser) has the same effect?

Any chance you have an insider Windows build?

**Comment by sa3eedo12** [comment]
Chrome has the same behavior as well.

I'm running the latest insider build, would you like me to share any logs?

**Comment by roman380** [comment]
I asked about insider build because you are the second person with this problem, I talked to another user who has unexpected failure in NVIDIA hardware encoder (that that other use NVIDIA runtime triggers "out of memory" error), for no apparent reason, and also on Insider build.

I tend to think that it's a software conflict with cause outside of Rainway, but I am interested in possible workaround. Also especially that it looks like other software can work with hardware encoder (maybe different mode).

Could you please do the following:

1. download an extract to temp directory: ~~[ProduceExperimentReport-20200130-A.zip]()~~ removed, [see fresher build below](https://github.com/RainwayApp/bug-tracker/issues/375#issuecomment-581020235)
2. run ProduceExperimentReport.exe and wait a bit while it's taking test recordings; when it's finished it will just pack everything into a Report-xxx file in the same directory. Please send this file back.
3. ~~There are two other apps in the archive: `MediaFoundationDxgiCapabilities-x64.exe` and `MediaFoundationDxgiCapabilities-x64 (Video Codec SDK 6.0.1).exe`; please run them once, they will show some text soon and you click Submit button there - they will post this content.~~

Thanks!

**Comment by sa3eedo12** [comment]
[Report-20200131-170652.zip](https://github.com/RainwayApp/bug-tracker/files/4139484/Report-20200131-170652.zip)

Here you go, hope this helps!

Thanks!

**Comment by roman380** [comment]
Thanks! I will check the report/minidumps and probably follow up.

From a a quick look - yes the problem is related to use of video encoder, some unobvious one, maybe related to driver update. The yesterday's case was a bit different: older card, and also older driver. Anyway I need to check the data and decide how to move on from there.

**Comment by roman380** [comment]
Also probably worth mentioning (for others) that here it is a "newer" Insider build 19555 while the yesterday case was on "somewhat older" but still Insider 19033.

**Comment by roman380** [comment]
OK, one another case with another NVIDIA GPU and again insider build

* Microsoft Windows 10.0.19551
* Error 0xCE56000C
* FileVersion 27.21.14.5012, FileDescription NVIDIA Video Encoder API, Version 8.0 , TimeDateStamp 1/4/2020 4:23:15 AM 1578111795
* Context: Adapter "NVIDIA GeForce GTX 970", LUID 0.0x0000D900, Output "\\.\DISPLAY2"; Adapter "NVIDIA GeForce GTX 970", LUID 0.0x0000D900, Output "\\.\DISPLAY1"

Something possibly related from recent on NVIDIA forum: https://devtalk.nvidia.com/default/topic/1069890/video-codec-and-optical-flow-sdk/possible-bug-forceidr-to-resend-sps-pps-does-not-work-in-d3d11-encoder-api-but-works-in-cuda/

**Comment by roman380** [comment]
@sa3eedo12 could you please re-create the report once again with this new build? I am guessing I see where the trouble comes from....

~~[ProduceExperimentReport-20200201.zip]()~~
[ProduceExperimentReport-20200229.zip](https://github.com/RainwayApp/bug-tracker/files/4270405/ProduceExperimentReport-20200229-44fc16e8ae87a57ac30920b84044d3e78ffb9dea.zip)

Instructions (pulled from above):

> 1. download an extract to temp directory: ProduceExperimentReport-20200130-A.zip removed, see fresher build below
> 2. run ProduceExperimentReport.exe and wait a bit while it's taking test recordings; when it's finished it will just pack everything into a Report-xxx.ZIP file in the same directory. Please send this Report-xxx.ZIP file back.

**Comment by roman380** [comment]
OK, in the meantime I upgraded one of my old boxes to insider Windows and I see the issue. Silly bug in  NVIDIA driver, or Windows changes that triggered this silly NVIDIA bug. We are going to have a workaround with next Rainway update, or just ping me here for a quick patch.

**Comment by roman380** [comment]
Fixed in Rainway 1.0.55
